version: '3'

volumes:
  db-data:
  grafana-data:

services:

  db:
    image: "postgres:latest"
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      API_USER: "${API_USER}"
      API_PASSWORD: "${API_PASSWORD}"
      API_ANON_USER: "${API_ANON_USER}"
      API_SCHEMA: "${API_SCHEMA}"
      DASHBOARD_DB_USER: "${DASHBOARD_DB_USER}"
      DASHBOARD_DB_PASSWORD: "${DASHBOARD_DB_PASSWORD}"
      DASHBOARD_DB_DATABASE: "${DASHBOARD_DB_DATABASE}"
      RESULTS_USER: "${RESULTS_USER}"
      RESULTS_PASSWORD: "${RESULTS_PASSWORD}"
      RESULTS_SCHEMA: "${RESULTS_SCHEMA}"
    volumes:
      - "./db-entrypoint:/docker-entrypoint-initdb.d"
      - "db-data:/var/lib/postgresql/data" # based on: https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes

  workbench: # https://hub.docker.com/r/dpage/pgadmin4/
    image: "dpage/pgadmin4:4.2"
    restart: always
    ports:
      - ${WORKBENCH_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"

  api: # docs: http://postgrest.org/en/v5.1/api.html
    image: "postgrest/postgrest:latest"
    restart: always
    ports:
      - ${API_PORT}:3000
    environment:
      PGRST_DB_URI: "postgres://${API_USER}:${API_PASSWORD}@db/${POSTGRES_DB}"
      PGRST_DB_ANON_ROLE: "${API_ANON_USER}"
      PGRST_DB_SCHEMA: "${API_SCHEMA}"
      PGRST_JWT_SECRET: "${API_JWT_SECRET}"
    depends_on:
      - db

  dashboard: # docs: http://docs.grafana.org/installation/docker/
    image: "grafana/grafana:master"
    restart: always
    ports:
      - ${DASHBOARD_PORT}:3000
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana-provisioning:/etc/grafana/provisioning"
    environment:
      DASHBOARD_DB_USER: "${DASHBOARD_DB_USER}"
      DASHBOARD_DB_PASSWORD: "${DASHBOARD_DB_PASSWORD}"
      DASHBOARD_DB_DATABASE: "${DASHBOARD_DB_DATABASE}"
      DASHBOARD_ADMIN_USER: "${DASHBOARD_ADMIN_USER}"
      DASHBOARD_ADMIN_PASSWORD: "${DASHBOARD_ADMIN_PASSWORD}"
      RESULTS_USER: "${RESULTS_USER}"
      RESULTS_PASSWORD: "${RESULTS_PASSWORD}"
      RESULTS_SCHEMA: "${RESULTS_SCHEMA}"
    depends_on:
      - db
