{
 "title": "Scoreboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Remaining Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "content": "<center>\n<h1>\nLast Submission\n</h1>\n</center>"
  },
  {
   "title": "Top 10 Teams",
   "type": "table",
   "gridPos": { "h": 21, "w": 10, "x": 4, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  team_name,\n  MAX(accuracy) AS accuracy\nFROM api.metrics\nGROUP BY team_name\nORDER BY accuracy DESC\nLIMIT 10\n;"
    }
   ]
  },
  {
   "title": "Top 10 Submissions",
   "type": "table",
   "gridPos": { "h": 21, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT * FROM api.metrics\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "was done",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT time - (interval '1h') AS time FROM api.last_submitter;"
    }
   ]
  },
  {
   "title": "by team",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT team_name FROM api.last_submitter;"
    }
   ]
  }
 ]
}